### ISSUE TITLE
Installation on Kibana 4.4.2 failed

### ISSUE THREAD

**Issue by deuntje** [sirensolutions/kibi_timeline_vis#12]
While installing kibi_timeline_vis on Kibana 4.4.2 I encountered this error:

```
# bin/kibana plugin -i kibi_timeline_vis -u file:///home/dennis/kibi_timeline_vis-0.1.2.tar.gz 
Installing kibi_timeline_vis
Attempting to transfer from file:///home/dennis/kibi_timeline_vis-0.1.2.tar.gz
Transferring 2539993 bytes....................
Transfer complete
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation was unsuccessful due to error "Optimizations failure.

    ERROR in ./installedPlugins/kibi_timeline_vis/public/webpackShims/vis.js
    Module not found: Error: Cannot resolve module 'bower_components/vis/dist/vis.min.css' in /opt/kibana/installedPlugins/kibi_timeline_vis/public/webpackShims
     @ ./installedPlugins/kibi_timeline_vis/public/webpackShims/vis.js 1:0-48
    
    ERROR in ./installedPlugins/kibi_timeline_vis/public/webpackShims/vis.js
    Module not found: Error: Cannot resolve module 'bower_components/vis/dist/vis.min.js' in /opt/kibana/installedPlugins/kibi_timeline_vis/public/webpackShims
     @ ./installedPlugins/kibi_timeline_vis/public/webpackShims/vis.js 2:17-64
"
```

I also tried the 2 previous versions with same result.

**Comment by jccq** [comment]
Hi Deuntje, 
at this time we're supporting this component only on Kibi, please use the latest version available at http://siren.solutions/kibi and it should work. Sorry for the inconvenience

**Comment by Crazyigor1987** [comment]
Hi jccq,

is this a bigger process to solve the problem?
I'd love to have it on Kibana!

**Comment by jccq** [comment]
If this is of high priority to you please contact us at info@siren.solutions
for a conversation about professional services

else please consider that Kibi frontend code is Apache licensed so that
anyone can grab a piece of it, fix it... and even commit to Kibana! :) we'd
be very happy if that was the case :) then its guaranteed to be supported
for the future (on Kibana too).




On Sun, Mar 20, 2016 at 9:32 PM, Crazyigor1987 <notifications@github.com>
wrote:

> Hi jccq,
>
> is this a bigger process to solve the problem?
> I'd love to have it on Kibana!
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/sirensolutions/kibi_timeline_vis/issues/12#issuecomment-199030333>
>



-- 
Giovanni Tummarello
CEO - SIREn Solutions

**Comment by scampi** [comment]
It now works with the version 0.1.3
