### ISSUE TITLE
Events number limit not being taken under account

### ISSUE THREAD

**Issue by JuanCarniglia** [sirensolutions/kibi_timeline_vis#15]
When creating an Timeline visualization, you can only change the Event Number Limit once, and get a new result. After that, no matter what number you input in the Event Number Limit textbox, it is ignored (on redraw), and you have to Refresh the whole page in order to get the chart filtered with your selection.

This is caused by the size parameter not being added to the json that conforms the group declaration, on the controller class. I'll PR the fix.

**Comment by jccq** [comment]
Juan there would be so much to improve in the timeline if you wish, let me
know if you'd like ideas.. ;))))))

On Tue, Apr 19, 2016 at 9:48 PM, Stéphane Campinas <notifications@github.com
> wrote:

> Closed #15 <https://github.com/sirensolutions/kibi_timeline_vis/issues/15>
> .
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/sirensolutions/kibi_timeline_vis/issues/15#event-633578486>
>



-- 
Giovanni Tummarello
CEO - SIREn Solutions

**Comment by JuanCarniglia** [comment]
I like the visualization as it is, I think is great work. Sure there are improvement points (like actually using D3… which would allow for animated transitions, zooming and panning). Divs are much too anchored to the DOM and might look awkward in some mobile resolutions (I'll test it on my phone).
Also there is a small glitch on the vis editor, where the chart does not resize when you hide the options pane (probably missing watching for some event), but it's definitely minor.

I'll try and put some time in it.

**Comment by jccq** [comment]
I am more thinking of the following  -  some are way too advanced! so just
for sharing thoughts really

a) configuration for what happens when one click to the event e.g. one
would send the user to the right dashboard and with the right filter (e.g.
a filter on the ID of the event). :)  same configuration as the enhanced
results table we have.

b) also i am not terribly satisfied by the stype sheet the "single events"
and "Segment events" they are too much visually alike.

Previously we had NO COLORED BOX for single events.. but instead only had
the colored spot.. this would be great except the colored spot was not
aligned with the dotted line.. (which instead started from the center of
the label). Now its more correct.. the dotted line startes in the middle of
the event BOX.. but the difference between an event BOX and a event segment
box is not very noticeable :)

c) - but this is big and requires us to discuss more - we have this idea of
"joins" that should be inplicit in certain widgets. E.g. the timeline is
really requiring this. if i look for "gio" i want to see "gio's events"
 from index a, b, c,d  at the moment this is done simply because the label
gio appears on the other indexes and via a text search , this should
instead be done with a relational vilter across events. This however is a
deeper refactoring which would allow (and wow!) to put a "company" widget
into the "Article" dashboard and have this work coherently via implicit
filters (both way both for visualizing and when something is clicked) -->
we call this concept foreign widgets

d) in general it might be a great time to introduce popups that show the
most important info about an entity. These are in practice a single line
data table which one could select in a configuration. e.g. over on event
one and see a line of the data table.. which then can be expanded to reveal
all the filters and the underlying json.

Gio

On Wed, Apr 20, 2016 at 11:03 PM, Juan Carniglia <notifications@github.com>
wrote:

> I like the visualization as it is, I think is great work. Sure there are
> improvement points (like actually using D3… which would allow for animated
> transitions, zooming and panning). Divs are much too anchored to the DOM
> and might look awkward in some mobile resolutions (I'll test it on my
> phone).
> Also there is a small glitch on the vis editor, where the chart does not
> resize when you hide the options pane (probably missing watching for some
> event), but it's definitely minor.
>
> I'll try and put some time in it.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/sirensolutions/kibi_timeline_vis/issues/15#issuecomment-212628281>
>



-- 
Giovanni Tummarello
CEO - SIREn Solutions
